<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<bug>
    <id>24778</id>
    <title>Panic in libnetwork.isManager()</title>
    <description>
        <paragraph id="1">
            <sentence id="1.1">Log: https://gist.github.com/tonistiigi/946ef6a8bf758c6ae4a59c1bae2a5395#file-daemon-log-L339</sentence>
        </paragraph>
        <paragraph id="2">
            <sentence id="2.1">Seen in: https://jenkins.dockerproject.org/job/Docker-PRs-experimental/21350/console</sentence>
        </paragraph>
        <paragraph id="3">
            <sentence id="3.1">"'
22:03:29 
22:03:29 ----------------------------------------------------------------------
22:03:29 FAIL: docker_api_swarm_test.go:568: DockerSwarmSuite.TestApiSwarmLeaveRemovesContainer
22:03:29 
22:03:29 [d50322686] waiting for daemon to start
22:03:29 [d50322686] daemon started
22:03:29 docker_api_swarm_test.go:582:
22:03:29 c.Assert(d.Leave(true), checker.IsNil)
22:03:29 ... value *errors.errorString = &amp;errors.errorString{s:"leaving swarm: invalid statuscode -1, \"\""} ("leaving swarm: invalid statuscode -1, \"\"")
22:03:29 
22:03:33 
22:03:33 ----------------------------------------------------------------------
"'</sentence>
        </paragraph>
        <paragraph id="4">
            <sentence id="4.1">@aboch @mavenugo</sentence>
        </paragraph>
    </description>
</bug>
