<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<bug>
	<id>TRUNK-3506</id>
	<title>The new order number test method fails randomly</title>
	<description>
		<paragraph id="1">
			<sentence id="1.1">The OrderServiceTest#getNewOrderNumber_shouldAlwaysReturnUniqueOrderNumbersWhenCalledMultipleTimesWithoutSavingOrders() test method starts multiple threads but is not thread safe.</sentence>
			<sentence id="1.2">This causes the test to fail randomly.</sentence>
			<sentence id="1.3">We should modify the test to be thread safe.</sentence>
			<sentence id="1.4">Thus when it fails, we will be confident that it signifies a defect in the code being tested.</sentence>
		</paragraph>
		<paragraph id="2">
			<sentence id="2.1">The thread safety issue is caused by having multiple threads that share a state in a non-thread safe {{HashSet}}.</sentence>
			<sentence id="2.2">This can be corrected by wrapping the set in a thread safe proxy using the {{Collections#synchronizedSet(Set)}} method.</sentence>
		</paragraph>
	</description>
</bug>
